services:
  mysql-db:
    image: mysql:8.0
    container_name: chat-sad-mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: chat_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: